version: '3.7'

services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/app
      - static_data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=crazylion101
      - ALLOWED_HOSTS=127.0.0.1
    depends_on:
      - db

  web:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - app
    volumes:
      - ./frontend:/app
      - static_data:/vol/www
    command: npm start
    restart: always

  proxy:
    image: proxy:latest
    depends_on:
      - app
      - web
    ports:
      - "8000:8000"
    volumes:
      - static_data:/vol/static
  
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=crazylion101

volumes:
  static_data:
