version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app
      - static_data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=crazylion101
      - ALLOWED_HOSTS=127.0.0.1
    depends_on:
      - db

  proxy:
    image: proxy:latest
    depends_on:
      - app
    ports:
      - "8000:8000"
    volumes:
      - static_data:/vol/static
  
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=crazylion101

volumes:
  static_data:
