version: '3.7'

services:
  app:
    build:
      context: ./app
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    ports:
    - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=crazylion101
    depends_on:
      - db

  web:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - app
    volumes:
      - ./frontend:/app
    command: npm start
    restart: always
  
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=crazylion101

volumes:
  static_data: