# Generated by Django 4.0.2 on 2022-02-28 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_watchlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerHistoricInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('volume', models.IntegerField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ticker')),
            ],
        ),
    ]
