# Generated by Django 4.0.2 on 2022-02-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tickerhistoricinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tickers',
            field=models.ManyToManyField(through='core.WatchlistItem', to='core.Ticker'),
        ),
    ]
