# Generated by Django 4.0.2 on 2022-03-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tickerhistoricinfo_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerhistoricinfo',
            name='date',
            field=models.DateField(max_length=10),
        ),
    ]
