# Generated by Django 4.0.2 on 2022-04-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_tickerhistoricinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
